import { useState, useEffect } from "react";
import type { NodeProps } from "reactflow";
import {
  IconSparkles,
  IconThumbUp,
  IconThumbDown,
  IconArrowBarLeft,
  IconArrowBarRight,
  IconArrowBarUp,
  IconArrowBarDown,
} from "@tabler/icons-react";

const F = "'Open Sans', sans-serif";

const SOURCES = ["WB Portfolio Data", "WDI", "Country CPF"];

interface NavLabels {
  left: string;
  up?: string;
  down?: string;
  right: string;
}

interface OutcomeAreaData {
  title: string;
  body: string;
  streamDelay?: number;
  index?: number;
  totalCards?: number;
  navLabels?: NavLabels;
  onNavDown?: () => void;
  onNavClick?: (label: string) => void;
}

function useStreamingText(fullText: string, delay: number): string {
  const [displayed, setDisplayed] = useState("");

  useEffect(() => {
    let timer: ReturnType<typeof setTimeout>;
    let interval: ReturnType<typeof setInterval>;

    timer = setTimeout(() => {
      let i = 0;
      interval = setInterval(() => {
        i += 2;
        setDisplayed(fullText.slice(0, i));
        if (i >= fullText.length) {
          setDisplayed(fullText);
          clearInterval(interval);
        }
      }, 8);
    }, delay);

    return () => {
      clearTimeout(timer);
      clearInterval(interval);
    };
  }, [fullText, delay]);

  return displayed;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function OutcomeAreaCard({ data, selected }: NodeProps<any>) {
  const { title, body, streamDelay = 0, index = 0, totalCards = 5, navLabels, onNavDown, onNavClick, connector, viewMode = false, playMode = false } = data as OutcomeAreaData & { connector?: string; viewMode?: boolean; playMode?: boolean };
  const displayed = useStreamingText(body, streamDelay + 150);
  const showCursor = displayed.length > 0 && displayed.length < body.length;
  const [hovered, setHovered] = useState(false);

  return (
    <div
      className="card-enter"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        animationDelay: `${streamDelay}ms`,
        width: playMode ? "100%" : 411,
        background: "#FFFFFF",
        border: playMode ? "none" : selected ? "1px solid #0b6fd3" : hovered ? "1px solid #BDBDBD" : "1px solid #E5E5E5",
        borderRadius: playMode ? 0 : 8,
        boxShadow: playMode ? "none" : selected ? "0px 0px 0px 3px rgba(11,111,211,0.12)" : hovered ? "0px 4px 12px rgba(0,0,0,0.08)" : "0px 4px 6px -1px rgba(0,0,0,0.05), 0px 2px 4px -1px rgba(0,0,0,0.03)",
        padding: 25,
        display: "flex",
        flexDirection: "column",
        gap: 16,
        fontFamily: F,
        cursor: playMode ? "default" : "grab",
        transition: "border-color 0.15s, box-shadow 0.15s",
      }}
    >
      {/* Label + Title + AI badge */}
      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        <span
          style={{
            fontSize: 12,
            color: "#9E9E9E",
            textTransform: "uppercase",
            letterSpacing: "0.5px",
            fontFamily: F,
            lineHeight: "1.4",
          }}
        >
          Outcome Area
        </span>

        <span
          style={{
            fontSize: 20,
            fontWeight: 600,
            color: "#000",
            lineHeight: "1.4",
            fontFamily: F,
            whiteSpace: "pre-line",
          }}
        >
          {title}
        </span>

        {/* Generated by AI */}
        <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
          <IconSparkles
            size={16}
            stroke={1.5}
            style={{
              flexShrink: 0,
              color: "#AE5DED",
            }}
          />
          <span
            style={{
              fontSize: 10,
              letterSpacing: -0.25,
              lineHeight: "1.4",
              background: "linear-gradient(to left, #68C5EA 19%, #AE5DED 123%)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              backgroundClip: "text",
              fontFamily: F,
            }}
          >
            Generated by AI
          </span>
        </div>
      </div>

      {/* Streaming body text — minHeight pre-reserves the full rendered height so
          the card doesn't grow and overlap cards below during streaming */}
      <p
        style={{
          margin: 0,
          fontSize: 16,
          color: "rgba(0,13,26,0.57)",
          lineHeight: "24px",
          fontFamily: F,
          minHeight: data.bodyMinHeight ?? 24,
        }}
      >
        {displayed}
        {showCursor && (
          <span
            className="stream-cursor"
            style={{
              display: "inline-block",
              width: 2,
              height: "1em",
              background: "#AE5DED",
              marginLeft: 1,
              verticalAlign: "text-bottom",
            }}
          />
        )}
      </p>

      {/* Navigation arrow-bar buttons — hidden in view/play mode */}
      {!viewMode && !playMode && (
        <div style={{ display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
          {(
            [
              { Icon: IconArrowBarLeft,  show: true,                    label: navLabels?.left  ?? "Back to overview",         onClickExtra: undefined },
              { Icon: IconArrowBarUp,    show: index > 0,               label: navLabels?.up    ?? "Previous outcome area",     onClickExtra: undefined },
              { Icon: IconArrowBarDown,  show: index < totalCards - 1,  label: navLabels?.down  ?? "Next outcome area",         onClickExtra: onNavDown },
              { Icon: IconArrowBarRight, show: true,                    label: navLabels?.right ?? "Explore deeper",            onClickExtra: undefined },
            ] as const
          )
            .filter((b) => b.show)
            .map(({ Icon, label, onClickExtra }) => (
              <button
                key={label}
                onClick={() => { onNavClick?.(label); onClickExtra?.(); }}
                style={{
                  background: "none",
                  border: "none",
                  fontFamily: F,
                  fontSize: 12,
                  color: "#086ED3",
                  fontWeight: 600,
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  gap: 4,
                  padding: 0,
                }}
              >
                <Icon size={13} stroke={2} />
                {label}
              </button>
            ))}
        </div>
      )}

      {/* Footer */}
      <div
        style={{
          borderTop: "1px solid #E5E5E5",
          paddingTop: 14,
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          gap: 8,
        }}
      >
        {/* Named source chips */}
        <div style={{ display: "flex", alignItems: "center", gap: 4, flexWrap: "wrap" }}>
          {connector && (
            <span style={{
              fontSize: 11, color: "#0B6FD3",
              background: "rgba(11,111,211,0.07)",
              border: "1px solid rgba(11,111,211,0.18)",
              borderRadius: 4, padding: "2px 6px",
              lineHeight: "1.4", whiteSpace: "nowrap", fontFamily: F,
            }}>
              {connector}
            </span>
          )}
          {SOURCES.map((src) => (
            <span
              key={src}
              style={{
                fontSize: 11,
                color: "#616161",
                background: "#F5F5F5",
                borderRadius: 4,
                padding: "2px 6px",
                lineHeight: "1.4",
                fontFamily: F,
                whiteSpace: "nowrap",
              }}
            >
              {src}
            </span>
          ))}
        </div>

        {/* Thumb up / down */}
        <div style={{ display: "flex", alignItems: "center", gap: 2, flexShrink: 0 }}>
          <button
            style={{
              background: "none",
              border: "none",
              padding: "3.5px",
              cursor: "pointer",
              color: "#616161",
              display: "flex",
              alignItems: "center",
              borderRadius: 100,
            }}
          >
            <IconThumbUp size={17} stroke={1.5} />
          </button>
          <button
            style={{
              background: "none",
              border: "none",
              padding: "3.5px",
              cursor: "pointer",
              color: "#616161",
              display: "flex",
              alignItems: "center",
              borderRadius: 100,
            }}
          >
            <IconThumbDown size={17} stroke={1.5} />
          </button>
        </div>
      </div>
    </div>
  );
}

export default OutcomeAreaCard;
